config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :people

  root 'home#index'

  # project routes
  get 'project/:id/histories' => 'project#histories'
  post 'project/store' => 'project#store'
  put  'project/:id/update' => 'project#update'
  get   'project/get'   => 'project#get'
  delete  'project/:id/destroy'   => 'project#destroy'

  # history routes
  post 'history/store' => 'history#store'
  put 'history/:id/update' => 'history#update'
  put 'history/:id/status' => 'history#status'
  put 'history/:id/finish' => 'history#finish'
  delete 'history/:id/destroy' => 'history#destroy'

  # task routes
  put 'task/:id/done' => 'task#done'
end

app/models/history.rb
class History < ActiveRecord::Base
    has_many :tasks, dependent: :destroy
    belongs_to :project
    belongs_to :requester, :class_name => "Person", :foreign_key => "requester_id"
    belongs_to :owner, :class_name => "Person", :foreign_key => "owner_id"

    # Validating fields
    validates :name, :status, :requester_id, presence: true

    # Finds histories and returns a hash separated by status
    def self.find_histories_by_status(project_id)
        # Sets empty hash
        histories = {"started": [], "pending": [], "delivered": []}

        if project_id

            # Finds the histories by status
            pending = History.where(status: "pending", project_id: project_id).to_json( :include => [:tasks])
            started = History.where(status: "started", project_id: project_id).to_json( :include => [:tasks])
            delivered = History.where(status: ["delivered", "accepted"], project_id: project_id).to_json( :include => [:tasks])

            # Creates hash with each state
            histories = {"started": started, "pending": pending, "delivered": delivered}
        end
        histories
    end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Validating fields
  validates :name, :role, :email, presence: true

  has_many :projects
  has_many :histories
end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :histories, dependent: :destroy
    belongs_to :manager, class_name: 'Person'
    # Validating fields
    validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :history
    # Validating fields
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_person!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :setPoints

  def setPoints
    @points = [1, 2, 3, 5, 8, 13]
  end

  protected
    def configure_permitted_parameters
      # Configuring accepted parameters to devise forms
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
    end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
    def store
        h = params[:history]
        history = History.new :name => h[:name], :description => h[:description], :deadline => h[:deadline], :owner_id => current_person.id, :project_id => params[:project_id], :points => h[:points], :requester_id => h[:requester_id], :status => 'pending'

        params[:tasks].each do |k|
            history.tasks.push(Task.new :description => k[:description], :done => false)
        end
        history.save
        render json: history.to_json(:include => [:tasks])
    end

    def update
        h = History.find_by :id => params[:id]
        
        h.update :name => params[:history][:name], :description => params[:history][:description], :deadline => params[:history][:deadline], :points => params[:history][:points], :requester_id => params[:history][:requester_id]

        h.tasks.delete_all
        params[:history][:tasks].each do |t|
           h.tasks.push(Task.new :description => t[:description], :done => t[:done]) 
        end
        h.save

        render json: h.to_json(:include => [:tasks])
    end

    def status
        h = History.find_by :id => params[:id]
        h.status = params[:status]
        if (params[:status] == 'started') && (h.started_at.nil?)
            h.started_at = DateTime.now.in_time_zone('Brasilia').to_time
        end
        h.save
        render json: h.errors.empty?
    end

    # Removes a history
    def destroy
        history = History.where(:id => params[:id])
        history.destroy(params[:id])
        
        render json: !history.exists?
    end

    def finish
        h = History.find_by :id => params[:id]
        updated = h.updated_at
        if !h.started_at.nil?
            h.finished_at = DateTime.now.in_time_zone('Brasilia').to_time
            h.save    
        end
        render json: updated != h.updated_at
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        # List projects by name and id
        @people = Person.pluck(:name, :id)
    end
end

app/controllers/project_controller.rb
# ProjectController. This handles with requests and returns
# project data
class ProjectController < ApplicationController
  # Histories method that returns the histories from a project
  # separated by status
  def histories
    # return json of histories
    render json: History.find_histories_by_status(params[:id])
  end

  # Store new project
  def store
    # try to create the new project
    project = Project.create(name: params[:name], manager_id: current_person.id)
    # returns the project object and possible errors messages
    render json: {project: project, errors: project.errors}
  end

  # Get list of projects
  def get
    render json: Project.select(:id, "name as label")
  end

  # Update project data
  def update
    # update project
    project = Project.update(params[:id], :name => params[:name])

    # returns if the data is updated
    render json: project.errors.empty?
  end

  # Removes a project
  def destroy
    project = Project.where(:id => params[:id])
    project.destroy(params[:id])
    
    render json: !project.exists?
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
    def done
        task = Task.find_by :id => params[:id]
        task.done = !task.done
        task.save
        render json: task.errors.empty?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/home/index.html.erb
<!-- Projects Row -->
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">To Do
      <a ng-show="select" class="pull-right" ng-click="newHistory()"><i class="glyphicon glyphicon-plus"></i></a>
      </div>
      <div class="panel-body containerVertical" data-status="pending">
        <div class="panel panel-default" ng-repeat="pending in histories.pending">
          <div class="panel-body" data-card-id="{{pending.id}}">
            <div class="col-md-10">
              <p>{{ pending.name }}</p>
            </div>
            <div class="dropdown col-md-2">
              <a href="javascript:;" class="dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-option-horizontal"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="javascript:;" ng-click="changeHistory($index, 'pending')">Edit</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="javascript:;" ng-click="rmHistory(pending.id, $index, 'pending')">Delete</a></li>
              </ul>
            </div>
            <div class="col-md-12">
              <p class="history-text pull-right">{{ percent(pending.tasks) | percentage:2 }}</p>
              <p class="history-text">Deadline: {{ pending.deadline | date:"yyyy/MM/dd HH:mm" : "UTC" }}</p>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">Doing</div>
      <div class="panel-body containerVertical" data-status="started">
        <div class="panel panel-default" ng-if="histories.started" ng-repeat="started in histories.started">
          <div class="panel-body" data-card-id="{{started.id}}">
            <div class="col-md-10">
              <p>{{ started.name }}</p>
            </div>
            <div class="dropdown col-md-2">
              <a href="javascript:;" class="dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-option-horizontal"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="javascript:;" ng-click="changeHistory($index, 'started')">Edit</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="javascript:;" ng-click="rmHistory(started.id, $index, 'started')">Delete</a></li>
              </ul>
            </div>
            <div class="col-md-12">
              <p class="history-text pull-right">{{ percent(started.tasks) | percentage:2 }}</p>
              <p class="history-text">Deadline: {{ started.deadline | date:"yyyy/MM/hh HH:mm" : "UTC" }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">Done</div>
      <div class="panel-body containerVertical" data-status="delivered">
        <div class="panel panel-default" ng-if="histories.delivered" ng-repeat="delivered in histories.delivered">
          <div class="panel-body" data-card-id="{{delivered.id}}">
            <div class="col-md-10">
              <p>{{ delivered.name }}</p>
            </div>
            <div class="dropdown col-md-2">
              <a href="javascript:;" class="dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="glyphicon glyphicon-option-horizontal"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="javascript:;" ng-click="changeHistory($index, 'delivered')">Edit</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="javascript:;" ng-click="rmHistory(delivered.id, $index, 'delivered')">Delete</a></li>
              </ul>
            </div>
            <div class="col-md-12">
              <p class="history-text pull-right">{{ percent(delivered.tasks) | percentage:2 }}</p>
              <p class="history-text">Deadline: {{ delivered.deadline | date:"yyyy/MM/hh HH:mm" : "UTC" }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<%= render partial: 'home/shared/history_modal'  %>

app/views/home/shared/_card.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <%= "Nome: " + name + " --- Descrição: " + description %>
    </div>
</div>

app/views/home/shared/_history_modal.html.erb
<div id="newHistoryModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <form ng-submit='saveHistory()'>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="historyTitelId">{{ !update ? 'New History' : 'Update History' }}</h4>
        </div>
        <div class="modal-body">
          <div class="row">
              <div class="col-md-4 form-group">
                <%= label_tag(:name, "Name:") %>
                <%= text_field_tag(:name, '', class: "form-control", 'ng-model': 'history.name') %>
              </div>
              <div class="col-md-3 form-group">
                <%= label_tag(:requester_id, "Requester:") %>
                <%= select_tag(:requester_id, options_for_select(@people), class: "form-control", 'ng-model': 'history.requester_id') %>
              </div>
              <div class="col-md-3 form-group">
                <%= label_tag(:deadline, "Deadline:") %>
                <%= text_field_tag(:deadline, '', {class: "form-control date", 'ng-model': 'history.deadline', 'ng-blur': 'deadlineBlur()'}) %>
              </div>
              <div class="col-md-2 form-group">
                <%= label_tag(:points, "Points:") %>
                <%= select_tag(:points, options_for_select(@points), class: "form-control", 'ng-model': 'history.points') %>
              </div>
              <div class="col-md-12">
                <%= label_tag(:description, "Description:") %>
                <%= text_area_tag(:description, "", class: "form-control", 'ng-model': 'history.description') %>
              </div>
          </div> 
          <hr/>
          <div class="row">
            <div class="col-md-12">
              <h4>Tasks</h4>
            </div>
            <div class="col-md-12">
              <div class="progress">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ taskPercent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ taskPercent }}%">
                  {{ taskPercent | percentage:2 }}
                </div>
              </div>
            </div>

            <div ng-repeat="task in history.tasks track by $index" class="col-md-12 panel">
              <div class="col-md-1 form-group">
                <input type="checkbox" ng-model="task.done" ng-click="taskDone(task.id)">
              </div>
              <div class="col-md-10 form-group">
                <input type="text" class="form-control" ng-show="!task.done" ng-model="task.description" name="task[{{$index}}]">
                <h5 ng-show="task.done"><strike>{{ task.description }}</strike></h5>
              </div>
              <div class="col-md-1" ng-click="rmHistory">
                <a ng-click="rmTask($index)"><i class="glyphicon glyphicon-minus"></i></a>
              </div>
            </div>
            <div class="pull-right col-md-2">
              <a ng-click="addTask()"><i class="glyphicon glyphicon-plus"></i> Add task</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
            <button type="button" ng-show="history.status == 'delivered'" ng-click="finish(history.id)" class="btn btn-default">Finish</button>
            <button type="submit" class="btn btn-default">{{ !update ? 'Save' : 'Save changes' }}</button>
        </div>
      </div><!-- /.modal-content -->
    </form>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/home/shared/_project_modal.html.erb
<div id="projectModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Select a project</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-9">
            <select
              id="projectDropdown"
              class="form-control"
              v-model="selectProject"
            >
              <option v-for="project in projects" v-bind:value="project.id">
                {{ project.label }}
              </option>
              
            </select>
          </div>
          <div class="col-md-1" ng-if="select">
            <button type="button" class="btn btn-danger pull-right" ng-click="rmProject(select)"><i class="glyphicon glyphicon-trash"></i></button>
          </div>
          <div class="col-md-2" ng-if="select">
            <button type="button" class="btn btn-primary pull-right" ng-click="selectProject()"><i class="glyphicon glyphicon-ok"></i> Select</button>
          </div>
        </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" @click="newProject()"><i class="glyphicon glyphicon-plus"></i> New Project</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="newProjectModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Set a name for your project</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-10">
            <input type="text" name="newProject" id="newProjectName" class="form-control" placeholder="Project name...">
          </div>
        </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" @click="saveNewProject()"><i class="glyphicon glyphicon-plus"></i> Save</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniTrello</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'classes/navbar', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="miniTrello" ng-controller="MainCtrl" ng-init="init()">

<div id="navigation">
  <%= render partial: "layouts/shared/navbar" %>
</div>
<!-- Page Content -->
<div class="container">
  <%= yield %>
</div>
<!-- /.container -->

</body>
</html>

app/views/layouts/shared/_navbar.html.erb
<!-- Navigation -->
<div class='notifications top-right'></div>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header col-md-6" id='project-selection'>
      <% if person_signed_in? %>
        <a class="navbar-brand" @click="changeProject" v-if="!enProjEdit">{{ projectName }}</a>
        <div class="col-md-6"  v-if="enProjEdit">
          <input type="text" class="form-control nav-input" v-model="projectName" />
        </div>
        <div class="col-md-6">
          <a class="navbar-brand" v-if="projectId" @click="enableEdit"><i class="glyphicon glyphicon-pencil"></i></a>
          <a class="navbar-brand" v-if="enProjEdit" @click="updateProject(projectName)"><i class="glyphicon glyphicon-ok"></i></a>
        </div>
      <% else %>
        <p class="navbar-brand"> Mini-trello</p>
      <% end %>
    </div>
    <div class="pull-right person_actions">
      <% if person_signed_in? %>
        <%= render partial: "layouts/shared/person_dropdown" %>
      <% end %>
    </div>
  </div>
  <!-- /.container -->
</nav>
<%= render partial: 'home/shared/project_modal'  %>

<script>
  var vueForm = new App.Navbar()
</script>

app/views/layouts/shared/_person_dropdown.html.erb
<div class="dropdown">
  <button class="btn btn-inverse dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <%= current_person.name %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "Edit", edit_person_registration_path, method: :get %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Sign out", destroy_person_session_path, method: :delete %></li>
  </ul>
</div>

app/views/people/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-default" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>